name: Update Publications from Google Scholar

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  update-publications:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scholarly requests
      
      - name: Update publications from Google Scholar
        run: python scripts/sync_publication_from_google_scholar.py
      
      - name: Check for changes
        id: git-check
        run: |
          git diff --quiet _data/publications.json || echo "changed=true" >> $GITHUB_OUTPUT
      
      - name: Commit and push if changed
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add _data/publications.json
          git commit -m "Update publications from Google Scholar"
          git push